import {useEffect, useState} from 'react';
import '../css/general_styles.css'
import { Link } from "react-router-dom";

function Playlists(props) {

  const [pl, setPl] = useState([])

  useEffect(() => {
    loadPlayLists()
  });

  let loadPlayLists = () => {
    fetch('http://127.0.0.1:5000/playlist', {
            method: 'GET',
            headers: {
              'Content-Type': 'application/json'
            }
        }).then(response => response.json())
        .then(data => setPl(data));
      let p = "Playlist King"
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      console.log(p);
      return pl;
  }

  return (
      <div className="text-format">
        <h1>Playlists</h1>
        {props.basicHeader === '' || props.basicHeader === undefined || props.basicHeader === null ? "": pl.map(item => {
          return <li>{item.playlist_name}</li>;
        })}
        {props.basicHeader === '' || props.basicHeader === undefined || props.basicHeader === null ? <Link to={'/login'} >Login</Link> : ""}
      </div>
    );
  }
  
  export default Playlists;